version: '3.8'

networks:
    demonstrator-network:

services:
    demonstrator-db:
        #image: docker.pkg.github.com/danielpreciado-marquez/mainzelhandler/mainzelhandler-demonstrator-db:0.0.1
        image: ghcr.io/danielpreciado-marquez/mainzelhandler-demonstrator-db:0.0.1
        build:
            context: ./db/
        container_name: demonstrator-db
        restart: always
        ports:
            - "3306:3306"
        networks:
            - demonstrator-network
        volumes:
            - ./volumes/demonstrator-db/data:/var/lib/mysql
    demonstrator-app:
        #image: docker.pkg.github.com/danielpreciado-marquez/mainzelhandler/mainzelhandler-demonstrator-app:0.0.1
        image: ghcr.io/danielpreciado-marquez/mainzelhandler-demonstrator-app:0.0.1
        build:
            context: ./app/
        container_name: demonstrator-app
        restart: always
        ports:
            - "8081:8081"
        networks:
            - demonstrator-network
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://demonstrator-db/demonstrator_db
            #- MAINZELHANDLER_MAINZELLISTE_URL=
            #- MAINZELHANDLER_MAINZELLISTE_API_KEY=
            #- MAINZELHANDLER_URL=
        depends_on:
            - demonstrator-db
