pseudonym-handler:
  mainzelliste:
    # url: https://zbb-mfm-dev.uni-muenster.de/mainzelliste/
    url: http://localhost:8080/
    api:
      key: 123BachelorArbeit321
      version: 3.0
  pseudonym-timeout: 600000
  request-path: /api
  url: http://host.docker.internal # 78.94.210.119
  useCallback: false

server:
  port: 8082
  servlet:
    context-path: /demonstrator
  # ssl:
  #   key-store: classpath:keystore.p12
  #   key-store-password: password
  #   key-store-type: pkcs12
  #   key-alias: tomcat
  #   key-password: password

spring:
  datasource:
    username: demonstrator-user
    password: demonstrator-password
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
