pseudonym-handler:
  mainzelliste:
    api:
      key: 123BachelorArbeit321
      version: 3.0
    url: http://host.docker.internal:8080
  pseudonym-timeout: 600000
  request-path: /api
  url: http://host.docker.internal
  useCallback: false

logging:
  level:
    root: INFO
  de:
    wwu:
      imi: DEBUG

server:
  port: 8081
  servlet:
    context-path: /demonstrator
  # ssl:
  #   key-store: classpath:keystore.p12
  #   key-store-password: password
  #   key-store-type: pkcs12
  #   key-alias: tomcat
  #   key-password: password

spring:
  datasource:
    username: demonstrator-user
    password: demonstrator-password
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
