mainzelliste:
  host: https://zbb-mfm-dev.uni-muenster.de
  url: ${mainzelliste.host}/mainzelliste/
  apikey: 123BachelorArbeit321

server:
  port: 8080
  servlet:
    context-path: /pseudonymizer

spring:
  datasource:
    username: demonstrator-user
    password: demonstrator-password
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
